name: deploy-feature

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create unique S3 bucket
        id: create_bucket
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          BUCKET_NAME="feature-${BRANCH_NAME}"
          echo "::set-output name=bucket_name::$BUCKET_NAME"
          aws s3api create-bucket --bucket $BUCKET_NAME

      - name: Configure bucket for static website hosting
        run: |
          aws s3 website s3://${{ steps.create_bucket.outputs.bucket_name }} --index-document index.html

      - name: Set bucket policy for public access
        run: |
          aws s3api put-bucket-policy --bucket ${{ steps.create_bucket.outputs.bucket_name }} --policy '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "PublicReadGetObject",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "s3:GetObject",
                  "Resource": "arn:aws:s3:::${{ steps.create_bucket.outputs.bucket_name }}/*"
                }
              ]
            }'

      - name: Deploy to S3
        run: aws s3 sync ./ s3://${{ steps.create_bucket.outputs.bucket_name }} --delete
      
      - name: Configure bucket public access settings
        run: |
          aws s3api put-public-access-block --bucket ${{ steps.create_bucket.outputs.bucket_name }} --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"